# Generated by Django 2.2 on 2019-05-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20190429_1314'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('isFeatured',)},
        ),
    ]
