# Generated by Django 2.2 on 2019-05-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20190503_1502'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='video',
            unique_together=set(),
        ),
    ]
