# Generated by Django 2.2 on 2019-04-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
    ]
