# Generated by Django 2.2 on 2019-04-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
