# Generated by Django 2.2.1 on 2019-05-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20190504_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
