# Generated by Django 2.2.4 on 2019-10-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20190518_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-updated']},
        ),
        migrations.AddField(
            model_name='album',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
